<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>MetroSystemForDotNet</RootNamespace>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <UseWindowsForms>True</UseWindowsForms>
    <AppDesignerFolder>Meteor Project</AppDesignerFolder>
    <ApplicationIcon>54nkr-kmnbe-001.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="app.config" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Windows" />
    <Import Include="System.Windows.Controls" />
    <Import Include="System.Windows.Data" />
    <Import Include="System.Windows.Documents" />
    <Import Include="System.Windows.Input" />
    <Import Include="System.Windows.Media" />
    <Import Include="System.Windows.Media.Imaging" />
    <Import Include="System.Windows.Navigation" />
    <Import Include="System.Windows.Shapes" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\WebSocketTest\WebSocketTest\WebSocketTest\bin\Debug\net10.0\WebSocketTest.dll" Link="libs\WebSocketTest.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MVSDK_Net">
      <HintPath>libs\MVSDKruntime\donet35\MVSDK_Net.dll</HintPath>
    </Reference>
    <Reference Include="WebSocketTest">
      <HintPath>..\..\WebSocketTest\WebSocketTest\WebSocketTest\bin\Debug\net10.0\WebSocketTest.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="Intel.ML.OnnxRuntime.OpenVino" Version="1.24.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4071-prerelease" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="NModbus" Version="4.0.0-alpha010" />
    <PackageReference Include="NModbus4" Version="3.0.0-alpha2" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260602" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260602" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260602" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260602" />
    <PackageReference Include="Sdcb.PaddleInference" Version="3.3.1" />
    <PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="3.3.1.70" />
    <PackageReference Include="Sdcb.PaddleOCR" Version="3.3.1" />
    <PackageReference Include="Sdcb.PaddleOCR.Models.Local" Version="3.3.1" />
    <PackageReference Include="Sdcb.PaddleOCR.Models.LocalV4" Version="2.7.0.1" />
    <PackageReference Include="System.Management" Version="11.0.0-preview.5.26302.115" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.14" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Meteor Project\configuration.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>configuration.settings</DependentUpon>
    </Compile>
    <Compile Update="Meteor Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Meteor Project\configuration.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>configuration.Designer.vb</LastGenOutput>
    </None>
    <None Update="Meteor Project\Settings.settings">
      <CustomToolNamespace>My</CustomToolNamespace>
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
    <None Update="UI\Languages\document\enUS.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="UI\Languages\document\zhCN.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="UI\Languages\document\zhTW.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="UI\Languages\document\jaJP.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\Correct.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\DecodeCompletedFlowFinished.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\DecodeCompletedPleaseOCR.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\DetectionPaused.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\DetectionReady.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\DetectionResumed.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\Error.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\MatchCompletedFlowFinished.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\MatchCompletedPleaseOCR.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\MatchCompletedPleaseScan.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\NoTemplate.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\SingleFlowCompleted.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\StageRecover.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\StageSkipped.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Voice\StageTimeout.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="54nkr-kmnbe-001.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="app.config" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="configuration\" />
  </ItemGroup>

</Project>
